wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.41.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718232751.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 2
      - 23
      4: 3.10.13
      5: 0.16.5
      6: 4.41.0.dev0
      8:
      - 4
      - 5
      13: darwin-arm64
